### ISSUE TITLE
Request to Complete GETTING_STARTED Instructions

### ISSUE THREAD

**Issue by Nuyoah0123** [DJNing/See_beyond_seeing#1]
Hey there, what a helpful project you've got! It's evident that a lot of hard work has gone into it, and I'm particularly interested in replicating some of the experiments mentioned in the README.

However, I noticed that the GETTING_STARTED file is currently marked as TODO. Would you mind adding the instructions there whenever you have a chance? It would make it a lot easier for me and others to dive into the code and get started with the experiments.

Thanks a bunch for your contributions to the community!

Cheers！

**Comment by gc625-kodifly** [comment]
Hi, sorry about that! I'll update the getting started doc in a few days, as I'm currently in Japan for ICRA. Cheers

**Comment by MrTooOldDriver** [comment]
@gc625-kodifly ping

**Comment by gc625-kodifly** [comment]
Hi @Nuyoah0123 [getting started page](https://github.com/DJNing/See_beyond_seeing/blob/main/docs/GETTING_STARTED.md) is now updated, apologies for the delay.
