### ISSUE TITLE
LiDAR results under the IoU of 0.5, 0.25, 0.25

### ISSUE THREAD

**Issue by XiangyPeng** [DJNing/See_beyond_seeing#2]
Hi, thank you for your great work!
I noticed that your results of LiDAR are based on the IoU of 0.7, 0.5, and 0.5, as Kitti format.
May I kindly ask if you have the results under the IoU of 0.5, 0.25, and 0.25 for cars, cyclists, and pedestrians for LiDAR point clouds? If not, could you please provide the configuration file or some guidance to obtain the results of 0.5, 0.25, and 0.25 IoU for LiDAR data?

**Comment by DJNing** [comment]
Hi, thanks for your interests in my work.

One simple way to obtain the required metric would be to modify the threshold here: https://github.com/DJNing/See_beyond_seeing/blob/0764453887a0ea85e08fcf2f9d916f7ea31ef8c0/pcdet/datasets/vod/vod_object_eval_python/eval.py#L639
