### ISSUE TITLE
No module named 'visual_utils'

### ISSUE THREAD

**Issue by 1879615351** [DJNing/See_beyond_seeing#3]
File "./demo.py", line 13, in <module>
    from visual_utils import visualize_utils as V
ModuleNotFoundError: No module named 'visual_utils'

Thanks for your work, I prompting the above error when testing the model with running toos/demo.py. Does the code provide this module less in the code?

**Comment by MrTooOldDriver** [comment]
Hi, thank you very much for spotting the missing files. We have pushed visual_utils to the main branch. Please fetch and pull from the main branch again. Thanks!
