### ISSUE TITLE
A spelling mistake in the"Training" part in GETTING_STARTED.md

### ISSUE THREAD

**Issue by eggman-1024** [DJNing/See_beyond_seeing#4]
Hi, there.
1. I found a spelling mistake in the"Training" part in GETTING_STARTED.md, where should be "**train**" but not "**trian**". So the command may be like this:

```bash
#LiDAR main modality, radar aux
bash ./tools/train_cfar_lidar.sh
#Radar main modality, LiDAR aux
bash ./tools/train_cfar_radar.sh
```

**Comment by DJNing** [comment]
Thank you for your correction
