### ISSUE TITLE
Have you use the radial velocity/compensated velocity of the 4D Radar

### ISSUE THREAD

**Issue by eggman-1024** [DJNing/See_beyond_seeing#5]
Hi! there,
Thanks for sharing such a great work!
When I review the detailed code , it seems that the velocity feature has not been used, but I am not sure, so I want to ask that have you use the radial velocity/compensated velocity of the 4D Radar?
Looking forward to your reply!

**Comment by DJNing** [comment]
Thank you for your interests in our work. For the used properties of point clouds, please check the dataset cfg for details (tools/cfgs/dataset_cfgs/vod_radar**.yaml)

**Comment by eggman-1024** [comment]
Thank you for your instruction,&nbsp;I have found that the ATTACH_USED_FEATURE_LIST&nbsp;in cfar-lidar.yaml is ['x ','y','z ','RCS']. Does this mean that you did not use radial velocity information?




3160391266
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DJNing/See_beyond_seeing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月3日(星期天) 晚上6:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DJNing/See_beyond_seeing] Have you use the radial velocity/compensated velocity of the 4D Radar (Issue #5)





 
Thank you for your interests in our work. For the used properties of point clouds, please check the dataset cfg for details (tools/cfgs/dataset_cfgs/vod_radar**.yaml)

**Comment by eggman-1024** [comment]
> Thank you for your interests in our work. For the used properties of point clouds, please check the dataset cfg for details (tools/cfgs/dataset_cfgs/vod_radar**.yaml)

Thank you for your instruction. I have found that the ATTACH_USED_FEATURE_LIST&nbsp;in cfar-lidar.yaml is ['x ','y','z ','RCS']. Does this mean that you did not use radial velocity information?

**Comment by DJNing** [comment]
Yes, the best results comes with this setting

**Comment by eggman-1024** [comment]
> Yes, the best results comes with this setting

Thanks!
